### ISSUE TITLE
Opraviť dizajnérske chyby

### ISSUE THREAD

**Issue by pknaus3** [pknaus3/KurzCademy.com#17]
- @bt7s7k7 - Ten Login/Register má graficku vadu pri scrollovani
- @SudoGMR  - V sekcii kurzy je horizontálny scroll bar (Vymazať)

**Comment by bt7s7k7** [comment]
U mňa hotovo. @pknaus3 nabudúce by si mohol pre každú vec urobiť zvlášť issue aby som ho mohol zatvoriť.
